In [116]:
import numpy as np
import pandas as pd


class InjectionListCreator:
    def __init__(self, location, start=1):
        self.location = location
        self.sample_names = pd.read_csv(self.location, header=None).squeeze().tolist()
        self.start = start
        self.dataframe = self.create_dataframe()
        self.count_dict = {}

    def create_dataframe(self):
        df = pd.DataFrame(
            {
                "sample": self.sample_names,
                "location": [
                    i for i in range(self.start, self.start + len(self.sample_names))
                ],
            }
        )
        return df

    def increment_unique_names(self, sample):
        if sample in self.count_dict:
            self.count_dict[sample] += 1
            if self.count_dict[sample] > 1:
                return sample + "_" + str(self.count_dict[sample])
        else:
            self.count_dict[sample] = 1
        return sample

    def return_list(self, target_dict, randomize=True):
        conditions = []
        choices = []
        for target_name, repeat_count in target_dict.items():
            conditions.append(self.dataframe["sample"].isin([target_name]))
            choices.append(repeat_count)

        extended = self.dataframe.iloc[
            self.dataframe.index.repeat(
                np.select(
                    condlist=conditions,
                    choicelist=choices,
                    default=1,
                )
            )
        ].reset_index(drop=True)

        extended["sample"] = extended["sample"].apply(self.increment_unique_names)

        if randomize:
            return extended.sample(frac=1)
        else:
            return extended

In [118]:
target_dict = {"blank_1": 5, "blank_2": 3, "qc_1": 2}

# Create an instance of InjectionListCreator
creator = InjectionListCreator("test.txt")

# Call the 'return_list' method on the instance and print the result
creator.return_list(target_dict, randomize=False)

       sample  location
0    sample_1         1
1    sample_2         2
2    sample_3         3
3    sample_4         4
4    sample_5         5
5    sample_6         6
6    sample_7         7
7    sample_8         8
8    sample_9         9
9   sample_10        10
10  sample_11        11
11  sample_12        12
12  sample_13        13
13  sample_14        14
14  sample_15        15
15  sample_16        16
16  sample_17        17
17  sample_18        18
18  sample_19        19
19  sample_20        20
20    blank_1        21
21  blank_1_2        21
22  blank_1_3        21
23  blank_1_4        21
24  blank_1_5        21
25    blank_2        22
26  blank_2_2        22
27  blank_2_3        22
28    blank_3        23
29       qc_1        24
30     qc_1_2        24
31       qc_2        25
32       qc_3        26